CREATE LOOKUP TABLE PRECIPITATION_SITUATION (CODE DOUBLE PRIMARY KEY, NAME VARCHAR (100));




INSERT INTO PRECIPITATION_SITUATION VALUES (1, 'Other');

INSERT INTO PRECIPITATION_SITUATION VALUES (2, 'Unknown');

INSERT INTO PRECIPITATION_SITUATION VALUES (3, 'No-Precipitation');

INSERT INTO PRECIPITATION_SITUATION VALUES (4, 'Unidentified-Slight');

INSERT INTO PRECIPITATION_SITUATION VALUES (5, 'Unidentified-Moderate');

INSERT INTO PRECIPITATION_SITUATION VALUES (6, 'Unidentified-Heavy');

INSERT INTO PRECIPITATION_SITUATION VALUES (7, 'Snow-Slight');

INSERT INTO PRECIPITATION_SITUATION VALUES (8, 'Snow-Moderate');

INSERT INTO PRECIPITATION_SITUATION VALUES (9, 'Snow-Heavy');

INSERT INTO PRECIPITATION_SITUATION VALUES (10, 'Rain-Slight');

INSERT INTO PRECIPITATION_SITUATION VALUES (11, 'Rain-Moderate');

INSERT INTO PRECIPITATION_SITUATION VALUES (12, 'Rain-Heavy');

INSERT INTO PRECIPITATION_SITUATION VALUES (13, 'Frozen-Precipitation-Slight');

INSERT INTO PRECIPITATION_SITUATION VALUES (14, 'Frozen-Precipitation-Moderate');

INSERT INTO PRECIPITATION_SITUATION VALUES (15, 'Frozen-Precipitation-Heavy');