CREATE LOOKUP TABLE PRECIPITATION_STATE (CODE DOUBLE PRIMARY KEY, NAME VARCHAR (100));


INSERT INTO PRECIPITATION_STATE VALUES (1, 'Precipitation');

INSERT INTO PRECIPITATION_STATE VALUES (2, 'No-Precipitation');

INSERT INTO PRECIPITATION_STATE VALUES (3, 'Error');

