CREATE TAG TABLE ENVIRONMENTAL (NAME VARCHAR(150) PRIMARY KEY, TIMESTAMP DATETIME BASETIME, VALUE DOUBLE SUMMARIZED, PARAMETER VARCHAR(100) NOT NULL, DEVICE_ID VARCHAR(50) NOT NULL);

CREATE ROLLUP _ENVIRONMENTAL_ROLLUP_HOUR ON ENVIRONMENTAL(VALUE) INTERVAL 1 HOUR EXTENSION;

CREATE ROLLUP _ENVIRONMENTAL_ROLLUP_MIN ON ENVIRONMENTAL(VALUE) INTERVAL 1 MIN EXTENSION;


CREATE INDEX IDX_PARAMETER ON ENVIRONMENTAL (PARAMETER) INDEX_TYPE TAG;
CREATE INDEX IDX_DEVICE_ID ON ENVIRONMENTAL (DEVICE_ID) INDEX_TYPE TAG;